#!/usr/bin/with-contenv bash
set -e

usercmd () { if [ "X${EUID}" != "X0" ]; then ${1} "${@:2}"; else s6-setuidgid ${PUID:-1000}:${PGID:-1000} ${1} "${@:2}"; fi; }

ROOTDIR="${ROOTDIR:-/config}";
WEBDIR="${WEBDIR:-$ROOTDIR/www}";
KANBOARDDIR="${KANBOARDDIR:-$WEBDIR/kanboard}"; # note: no ending /
# KANBOARD_WORKER_ARGS="";

cd ${KANBOARDDIR} || exit 1;

usercmd \
exec \
    ./cli worker \
    ${KANBOARD_WORKER_ARGS};
