#!/usr/bin/with-contenv bash
set -e

ROOTDIR="${ROOTDIR:-/config}";
WEBDIR="${WEBDIR:-$ROOTDIR/www}";
KANBOARDDIR="${KANBOARDDIR:-$WEBDIR/kanboard}"; # note: no ending /
# KANBOARD_BEANSTALKD_ARGS="";
#
cd ${KANBOARDDIR} || exit 1;

s6-setuidgid ${S6_USER:-alpine} \
exec \
    beanstalkd \
    ${KANBOARD_BEANSTALKD_ARGS};
